import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001e2f",
        "error-container": "#93000a",
        "outline": "#849495",
        "surface-variant": "#32353c",
        "background": "#10131a",
        "secondary-container": "#3131c0",
        "outline-variant": "#3b494b",
        "tertiary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#00dbe9",
        "on-error-container": "#ffdad6",
        "secondary": "#c0c1ff",
        "surface-container-lowest": "#0b0e14",
        "on-secondary-container": "#b0b2ff",
        "surface-container-highest": "#32353c",
        "error": "#ffb4ab",
        "surface-container": "#1d2026",
        "tertiary-container": "#b4deff",
        "surface-tint": "#00dbe9",
        "tertiary-fixed-dim": "#89ceff",
        "on-primary-fixed": "#002022",
        "on-secondary-fixed": "#07006c",
        "inverse-on-surface": "#2e3037",
        "on-tertiary": "#00344d",
        "surface-dim": "#10131a",
        "on-tertiary-container": "#006591",
        "on-surface": "#e1e2eb",
        "primary": "#dbfcff",
        "on-background": "#e1e2eb",
        "inverse-surface": "#e1e2eb",
        "secondary-fixed": "#e1e0ff",
        "tertiary": "#eef6ff",
        "on-surface-variant": "#b9cacb",
        "on-primary-fixed-variant": "#004f54",
        "inverse-primary": "#006970",
        "primary-fixed": "#7df4ff",
        "surface-bright": "#363940",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-primary": "#00363a",
        "on-error": "#690005",
        "surface": "#10131a",
        "secondary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-primary-container": "#006970",
        "primary-container": "#00f0ff",
        "surface-container-high": "#272a31",
        "on-secondary": "#1000a9",
        "surface-container-low": "#191c22",
        "emerald": "#34e0a1",
        "amber": "#ffcf5c",
        "violet": "#b794ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "gutter": "16px",
        "unit": "4px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "data-sm": ["'JetBrains Mono'", "monospace"],
        "label-caps": ["'JetBrains Mono'", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "data-lg": ["'JetBrains Mono'", "monospace"],
        "display-lg": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "mono": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "data-sm": ["13px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "data-lg": ["18px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
